# Artificial Neural Network
* Use Classification

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.12.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [16]:
dataset = pd.read_csv('Churn_Modelling.csv')

# column from 'CreditScore' to 'EstimatedSalary'
x = dataset.iloc[:, 3:-1].values

# output = Exited (O or 1)
y = dataset.iloc[:, -1].values

In [17]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [18]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [19]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

In [21]:
x[:, 2] = label_encoder.fit_transform(x[:, 2])
print(x[:, 2])

[0 0 0 ... 0 1 0]


One Hot Encoding the "Geography" column

In [26]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
column_transformer = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')

x = np.array(column_transformer.fit_transform(x))

In [27]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [28]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [30]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

## Part 2 - Building the ANN
* ANN - Artifical Neural Network
* Use Keras library in TensorFlow 2.0

### Initializing the ANN

In [33]:
# initialize the layer as sequence in ann
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [37]:
# number of neurons(features) want to have in the layer : try different parameters
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### Adding the second hidden layer

In [38]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### Adding the output layer
* sigmoid activation function
> also give the probability : 0 or 1

In [41]:
# unit has to be replaced to 1, since our output is binary(0 or 1).
# one output neuron is encoding the dependent variable.
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN
* accuracy score : evaluation 

In [42]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set
* batch learning is more efficient than stochastic gradient descent method in general
> but! it's depending on dataset

* epochs : iternation # for the training dataset
> if epochs is too small, the result tends to be overfitting. 

In [44]:
# batch_size = 32 (default)
# epochs : iternation # for the training dataset
ann.fit(x_train,y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4919 - accuracy: 0.7960
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4710 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4560 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4485 - accuracy: 0.7960
Epoch 5/100
250/250 [==============================] - 0s 979us/step - loss: 0.4435 - accuracy: 0.7960
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4401 - accuracy: 0.7960
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4368 - accuracy: 0.7960
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4339 - accuracy: 0.7960
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4314 - accuracy: 0.7960
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4287 - accu

250/250 [==============================] - 0s 937us/step - loss: 0.3421 - accuracy: 0.8625
Epoch 82/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3413 - accuracy: 0.8649
Epoch 83/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3413 - accuracy: 0.8631
Epoch 84/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3412 - accuracy: 0.8649
Epoch 85/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3411 - accuracy: 0.8627
Epoch 86/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3409 - accuracy: 0.8636
Epoch 87/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3413 - accuracy: 0.8631
Epoch 88/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3401 - accuracy: 0.8630
Epoch 89/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3400 - accuracy: 0.8635
Epoch 90/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3401 - accuracy

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank:

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer?

### Solution

* France -> OneHotEncoder
> find the 'France' dummay variable by observation above : [1,0,0]
 
 > the dummy variables are always created in the first columns.

* Male -> LabelEncoder
> male : 1, female : 0

* threshold : 0.5 

In [57]:
# apply the scaling before prediction : StandardScaler()
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])) > 0.5 )


1/1 [==============================] - 0s 18ms/step
[[False]]


### Conclusion for the given customer info

Therefore, our ANN model predicts that this customer stays in the bank!

=> **The customer won't leave our company**


**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [58]:
y_pred = ann.predict(x_test)

# classify the customer by threshold 0.5
# true(1): leave | false(0) : stay 
y_pred = (y_pred > 0.5)

print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))


63/63 [==============================] - 0s 760us/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [59]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1507   88]
 [ 198  207]]


0.857