### Data Encoding

* Label encoding

In [2]:
from sklearn.preprocessing import LabelEncoder

items=['TV','frige','microwave','computer','fan','fan','mixer','mixer']

# Create LabelEncoder object, perfore encoding with fit(), transform().
encoder = LabelEncoder()
# fit() used a lot in scikit-learn, it could be used when we do fit()&predit() in supervised learning and this case : fit()->transform()
encoder.fit(items)
labels = encoder.transform(items)
print('Encoding Value:',labels)

Encoding Value: [0 3 4 1 2 2 5 5]


In [3]:
print('Encoding class:',encoder.classes_)

Encoding class: ['TV' 'computer' 'fan' 'frige' 'microwave' 'mixer']


In [5]:
# inverse_transform : convert number to string value
print('Decoding Original value:',encoder.inverse_transform([4, 5, 2, 0, 1, 1, 3, 3]))

Decoding Original value: ['microwave' 'mixer' 'fan' 'TV' 'computer' 'computer' 'frige' 'frige']


* One-Hot encoding

In [9]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items=['TV','frige','microwave','computer','fan','fan','mixer','mixer']

# convert it to two-dimensional ndarray.
items = np.array(items).reshape(-1, 1)

# apply one-hot encoding : fit_transform()
oh_encoder = OneHotEncoder()
oh_labels = oh_encoder.fit_transform(items)

# the converted result of OneHotEncoder is Sparse Matrix, so it needs to be converted to Dense Matrix by toarray().
print('one-hot encoding data')
print(oh_labels.toarray())
print('one-hot encoding data shape :', oh_labels.shape )

one-hot encoding data
[[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]]
one-hot encoding data shape : (8, 6)


In [10]:
import pandas as pd

df = pd.DataFrame({'item':['TV','frige','microwave','computer','fan','fan','mixer','mixer'] })
pd.get_dummies(df)

item_TV  item_computer  item_fan  item_frige  item_microwave  item_mixer
0        1              0         0           0               0           0
1        0              0         0           1               0           0
2        0              0         0           0               1           0
3        0              1         0           0               0           0
4        0              0         1           0               0           0
5        0              0         1           0               0           0
6        0              0         0           0               0           1
7        0              0         0           0               0           1

### Featrue Scaling and standardization

* StandardScaler

In [12]:
from sklearn.datasets import load_iris
import pandas as pd
# Load Iris datasets and convert to DataFrame.
iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)

print('mean of feature values')
print(iris_df.mean())
print('\nthe variation of feature vaules')
print(iris_df.var())


mean of feature values
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

the variation of feature vaules
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [15]:
from sklearn.preprocessing import StandardScaler

# create StandardScaler object
scaler = StandardScaler()
# convert the datasets to StandardScaler. call fit( ), transform( ).
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

# after transform( ) the dataset's scale changed to numpy ndarry, so it needs to be converted to DataFrame.
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('mean of feature values')
print(iris_df_scaled.mean())
print('\nthe variation of feature vaules')
print(iris_df_scaled.var())

mean of feature values
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

the variation of feature vaules
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


* MinMaxScaler

In [16]:
from sklearn.preprocessing import MinMaxScaler

# create MinMaxScaler object.
scaler = MinMaxScaler()
# convert the datasets to MinMaxScaler. call fit(), transform().
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

# after transform( ) the dataset's scale changed to numpy ndarry, so it needs to be converted to DataFrame.
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('min of feature values')
print(iris_df_scaled.min())
print('\nmax of feature values')
print(iris_df_scaled.max())


min of feature values
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

max of feature values
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


* NOTE! Use Scaler to training and test dataset applying fit(), transform(), fit_transform().

In [19]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

# training data set is created with values ranging from 0 to 10, while the test data set is created with values ranging from 0 to 5.
# methods fit() and transform() of the Scaler class only accept 2-dimensional data. Therefore, you need to reshape the data using reshape(-1, 1) to change its dimension to a 2-dimensional array.
train_array = np.arange(0, 11).reshape(-1, 1)
test_array =  np.arange(0, 6).reshape(-1, 1)

In [20]:
# To create a MinMaxScaler object that transforms the data to have a minimum value of 0 and a maximum value of 1.
scaler = MinMaxScaler()

# after fit(), min of train_array 0 and max will be 10.  
scaler.fit(train_array)

# the train_array converted with 1/10 scale, the original will be converted 10-> 1
train_scaled = scaler.transform(train_array)
 
print('original train_array data:', np.round(train_array.reshape(-1), 2))
print('train_array data after Scaling :', np.round(train_scaled.reshape(-1), 2))

original train_array data: [ 0  1  2  3  4  5  6  7  8  9 10]
train_array data after Scaling : [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [21]:
# If you call the fit() method on the MinMaxScaler object using the test_array, the minimum and maximum values of the test data will be used to determine the scaling factors. 
# min of original data :0, max :5
scaler.fit(test_array)
# test_array converted with 1/5 scale. original will be conveted 5->1.  
test_scaled = scaler.transform(test_array)
# print converted train_array
print('original test_array data:', np.round(test_array.reshape(-1), 2))
print('test_array data after scaling:', np.round(test_scaled.reshape(-1), 2))


original test_array data: [0 1 2 3 4 5]
test_array data after scaling: [0.  0.2 0.4 0.6 0.8 1. ]


In [22]:
scaler = MinMaxScaler()
scaler.fit(train_array)
train_scaled = scaler.transform(train_array)
print('original train_array data:', np.round(train_array.reshape(-1), 2))
print('train_array data after scaling:', np.round(train_scaled.reshape(-1), 2))

# when you want to apply the scaling transformation to the test_array using the MinMaxScaler object, you should not call the fit() method again.
# only transform()! 
test_scaled = scaler.transform(test_array)
print('\noriginal test_array data:', np.round(test_array.reshape(-1), 2))
print('test_array data after Scaling:', np.round(test_scaled.reshape(-1), 2))


original train_array data: [ 0  1  2  3  4  5  6  7  8  9 10]
train_array data after scaling: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]

original test_array data: [0 1 2 3 4 5]
test_array data after Scaling: [0.  0.1 0.2 0.3 0.4 0.5]
